"""empty message

Revision ID: 49fc5c6e345c
Revises: 53c405ac8418
Create Date: 2020-03-24 20:03:07.291554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fc5c6e345c'
down_revision = '53c405ac8418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'set_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'set_password_token_expiry', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.create_unique_constraint(None, 'users', ['set_password_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.drop_column('users', 'set_password_token_expiry')
    op.drop_column('users', 'set_password_token')
    # ### end Alembic commands ###
